import type { Metadata } from 'next'
import '../globals.css'
import Header from 'components/Header'
import SideMenu from 'components/SideMenu'
import { Inter } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Healphy',
  description: 'Generated by create next app',
  icons: {
    icon: '/icons/favicon.png',
  },
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
})

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR" className={inter.className}>
      <body className="w-full bg-slate-600">
        <div>
          <Header />
          <div className="flex bg-zinc-100">
            <SideMenu />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
